<?php
$jieqiCollect['sitename'] = '落秋';
$jieqiCollect['siteurl'] = 'www.luoqiu.com';
$jieqiCollect['subarticleid'] = 'floor($articleid/1000)';
$jieqiCollect['subchapterid'] = '';
$jieqiCollect['proxy_host'] = '';
$jieqiCollect['proxy_port'] = '';
$jieqiCollect['autoclear'] = '0';
$jieqiCollect['defaultfull'] = '0';
$jieqiCollect['referer'] = '1';
$jieqiCollect['pagecharset'] = 'auto';
$jieqiCollect['urlarticle'] = 'http://www.luoqiu.com/book/<{subarticleid}>/<{articleid}>.html';
$jieqiCollect['articletitle']['left'] = '<h1>';
$jieqiCollect['articletitle']['right'] = '</h1>';
$jieqiCollect['articletitle']['middle'] = '!!!!';
$jieqiCollect['author']['left'] = '<span class="author">作者：<a href="!" target="_blank">';
$jieqiCollect['author']['right'] = '</a></span>';
$jieqiCollect['author']['middle'] = '!!!!';
$jieqiCollect['sort']['left'] = '本书属于<a class="type" href="~~~" target="_blank">';
$jieqiCollect['sort']['right'] = '</a>小说<br />';
$jieqiCollect['sort']['middle'] = '!!!!';
$jieqiCollect['keyword']['left'] = '<meta name="keywords" content="';
$jieqiCollect['keyword']['right'] = '" />';
$jieqiCollect['keyword']['middle'] = '!!!!';
$jieqiCollect['intro']['left'] = '<!--内容简介-->';
$jieqiCollect['intro']['right'] = '<!--评论列表-->';
$jieqiCollect['intro']['middle'] = '****';
$jieqiCollect['articleimage']['left'] = '<<img src="';
$jieqiCollect['articleimage']['right'] = '"></a></div>';
$jieqiCollect['articleimage']['middle'] = '~~~~';
$jieqiCollect['filterimage'] = 'nocover.jpg';
$jieqiCollect['indexlink']['left'] = '<a class="ll redbtn" href="~~~~" target="_blank" title="';
$jieqiCollect['indexlink']['right'] = '"><span>点击阅读';
$jieqiCollect['indexlink']['middle'] = '!!!!';
$jieqiCollect['fullarticle'] = '已完成';
$jieqiCollect['sortid']['玄幻魔法'] = '1';
$jieqiCollect['sortid']['武侠修真'] = '2';
$jieqiCollect['sortid']['都市言情'] = '3';
$jieqiCollect['sortid']['穿越小说'] = '4';
$jieqiCollect['sortid']['女性言情'] = '5';
$jieqiCollect['sortid']['游戏动漫'] = '6';
$jieqiCollect['sortid']['科幻小说'] = '7';
$jieqiCollect['sortid']['恐怖悬疑'] = '8';
$jieqiCollect['sortid']['散文诗词'] = '9';
$jieqiCollect['sortid']['其他类型'] = '10';
$jieqiCollect['urlindex'] = 'http://www.luoqiu.com/html/<{subarticleid}>/<{articleid}>/index.html';
$jieqiCollect['volume'] = '<span class="v">!!!</span>';
$jieqiCollect['chapter']['left'] = '<span><a href="$.html">';
$jieqiCollect['chapter']['right'] = '</a></span>';
$jieqiCollect['chapter']['middle'] = '!!!!';
$jieqiCollect['chapterid']['left'] = '<span><a href="';
$jieqiCollect['chapterid']['right'] = '.html">!</a></span>';
$jieqiCollect['chapterid']['middle'] = '$$$$';
$jieqiCollect['urlchapter'] = 'http://www.luoqiu.com/html/<{subarticleid}>/<{articleid}>/<{chapterid}>.html';
$jieqiCollect['content']['left'] = '<DIV id=content name="content">';
$jieqiCollect['content']['right'] = '<p></DIV>';
$jieqiCollect['content']['middle'] = '****';
$jieqiCollect['contentfilter'] = 'http://www.linezing.com
http://www.kuyuenet.com
(快捷键:←)!(快捷键:→)';
$jieqiCollect['contentreplace'] = '';
$jieqiCollect['collectimage'] = '1';
$jieqiCollect['imagetranslate'] = '0';
$jieqiCollect['addimagewater'] = '0';
$jieqiCollect['imagebgcolor'] = '';
$jieqiCollect['imageareaclean'] = '';
$jieqiCollect['imagecolorclean'] = '';
$jieqiCollect['listcollect'] = '';

?>
